image: node:16.13.2

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@14.2.3
  - npm install
  - ng build --base-href /tp-final-project
  - mkdir -p public
  - mv dist/tp-final-project* public/
  artifacts:
    paths:
    - public
  only:
  - main
  - pages