import { Album, AlbumItem } from 'src/app/core/models/album.models';

export const albumMockData = [
  {
    album_type: 'album',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX',
        },
        href: 'https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX',
        id: '1TA5sGRlKUJXBN4ZyJuDIX',
        name: 'Blessd',
        type: 'artist',
        uri: 'spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX',
        images: [
          {
            height: 0,
            url: 'string',
            width: 0,
          },
        ],
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/4PR6koe67C7YosjAYriYh4',
    },
    href: 'https://api.spotify.com/v1/albums/4PR6koe67C7YosjAYriYh4',
    id: '4PR6koe67C7YosjAYriYh4',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b2734c88949535e3089844c61219',
        width: 640,
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e024c88949535e3089844c61219',
        width: 300,
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d000048514c88949535e3089844c61219',
        width: 64,
      },
    ],
    name: 'Siempre Blessd',
    release_date: '2022-11-03',
    release_date_precision: 'day',
    total_tracks: 13,
    type: 'album',
    uri: 'spotify:album:4PR6koe67C7YosjAYriYh4',
  },
  {
    album_type: 'single',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/77ziqFxp5gaInVrF2lj4ht',
        },
        href: 'https://api.spotify.com/v1/artists/77ziqFxp5gaInVrF2lj4ht',
        id: '77ziqFxp5gaInVrF2lj4ht',
        name: 'Sech',
        type: 'artist',
        uri: 'spotify:artist:77ziqFxp5gaInVrF2lj4ht',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/1yENOcHrdeylQ4Mjy1DQJX',
    },
    href: 'https://api.spotify.com/v1/albums/1yENOcHrdeylQ4Mjy1DQJX',
    id: '1yENOcHrdeylQ4Mjy1DQJX',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b273d9bae3fb6c6ac1c5aa67744f',
        width: 640,
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e02d9bae3fb6c6ac1c5aa67744f',
        width: 300,
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d00004851d9bae3fb6c6ac1c5aa67744f',
        width: 64,
      },
    ],
    name: 'Ya Casi Vienen',
    release_date: '2022-10-28',
    release_date_precision: 'day',
    total_tracks: 4,
    type: 'album',
    uri: 'spotify:album:1yENOcHrdeylQ4Mjy1DQJX',
  },
  {
    album_type: 'album',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/27vNK840zYq6IfDijHPsv1',
        },
        href: 'https://api.spotify.com/v1/artists/27vNK840zYq6IfDijHPsv1',
        id: '27vNK840zYq6IfDijHPsv1',
        name: 'Gilberto Santa Rosa',
        type: 'artist',
        uri: 'spotify:artist:27vNK840zYq6IfDijHPsv1',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/4uBIS6rAEZQX8NCDgoLKq2',
    },
    href: 'https://api.spotify.com/v1/albums/4uBIS6rAEZQX8NCDgoLKq2',
    id: '4uBIS6rAEZQX8NCDgoLKq2',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b27383c59f3102bcc5eccc985475',
        width: 640,
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e0283c59f3102bcc5eccc985475',
        width: 300,
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d0000485183c59f3102bcc5eccc985475',
        width: 64,
      },
    ],
    name: 'Debut y Segunda Tanda (Deluxe)',
    release_date: '2022-10-28',
    release_date_precision: 'day',
    total_tracks: 10,
    type: 'album',
    uri: 'spotify:album:4uBIS6rAEZQX8NCDgoLKq2',
  },
  {
    album_type: 'album',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1vqR17Iv8VFdzure1TAXEq',
        },
        href: 'https://api.spotify.com/v1/artists/1vqR17Iv8VFdzure1TAXEq',
        id: '1vqR17Iv8VFdzure1TAXEq',
        name: 'LIT killah',
        type: 'artist',
        uri: 'spotify:artist:1vqR17Iv8VFdzure1TAXEq',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/1O0VHFd6xTl1CfLausE0kN',
    },
    href: 'https://api.spotify.com/v1/albums/1O0VHFd6xTl1CfLausE0kN',
    id: '1O0VHFd6xTl1CfLausE0kN',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b273618c9be5ab68c6663b5271b4',
        width: 640,
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e02618c9be5ab68c6663b5271b4',
        width: 300,
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d00004851618c9be5ab68c6663b5271b4',
        width: 64,
      },
    ],
    name: 'SnipeZ',
    release_date: '2022-10-27',
    release_date_precision: 'day',
    total_tracks: 13,
    type: 'album',
    uri: 'spotify:album:1O0VHFd6xTl1CfLausE0kN',
  },
  {
    album_type: 'album',
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1hcdI2N1023RvSwLzTtdsp',
        },
        href: 'https://api.spotify.com/v1/artists/1hcdI2N1023RvSwLzTtdsp',
        id: '1hcdI2N1023RvSwLzTtdsp',
        name: 'Natalia Lafourcade',
        type: 'artist',
        uri: 'spotify:artist:1hcdI2N1023RvSwLzTtdsp',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    external_urls: {
      spotify: 'https://open.spotify.com/album/4BJoDX0fIjR4RsFF4vyd81',
    },
    href: 'https://api.spotify.com/v1/albums/4BJoDX0fIjR4RsFF4vyd81',
    id: '4BJoDX0fIjR4RsFF4vyd81',
    images: [
      {
        height: 640,
        url: 'https://i.scdn.co/image/ab67616d0000b273164f6eeb838f0a702d9d6319',
        width: 640,
      },
      {
        height: 300,
        url: 'https://i.scdn.co/image/ab67616d00001e02164f6eeb838f0a702d9d6319',
        width: 300,
      },
      {
        height: 64,
        url: 'https://i.scdn.co/image/ab67616d00004851164f6eeb838f0a702d9d6319',
        width: 64,
      },
    ],
    name: 'De Todas las Flores',
    release_date: '2022-10-28',
    release_date_precision: 'day',
    total_tracks: 12,
    type: 'album',
    uri: 'spotify:album:4BJoDX0fIjR4RsFF4vyd81',
  },
];

export const albumWithTracksMockData = {
  album_type: 'album',
  artists: [
    {
      external_urls: {
        spotify: 'https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX',
      },
      href: 'https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX',
      id: '1TA5sGRlKUJXBN4ZyJuDIX',
      name: 'Blessd',
      type: 'artist',
      uri: 'spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX',
    },
  ],
  available_markets: [
    'AD',
    'AE',
    'AG',
    'AL',
    'AM',
    'AO',
    'AR',
    'AT',
    'AU',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BN',
    'BO',
    'BR',
    'BS',
    'BT',
    'BW',
    'BZ',
    'CA',
    'CD',
    'CG',
    'CH',
    'CI',
    'CL',
    'CM',
    'CO',
    'CR',
    'CV',
    'CW',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'FI',
    'FJ',
    'FM',
    'FR',
    'GA',
    'GB',
    'GD',
    'GE',
    'GH',
    'GM',
    'GN',
    'GQ',
    'GR',
    'GT',
    'GW',
    'GY',
    'HK',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IQ',
    'IS',
    'IT',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KR',
    'KW',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MG',
    'MH',
    'MK',
    'ML',
    'MN',
    'MO',
    'MR',
    'MT',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NE',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NR',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PG',
    'PH',
    'PK',
    'PL',
    'PS',
    'PT',
    'PW',
    'PY',
    'QA',
    'RO',
    'RS',
    'RW',
    'SA',
    'SB',
    'SC',
    'SE',
    'SG',
    'SI',
    'SK',
    'SL',
    'SM',
    'SN',
    'SR',
    'ST',
    'SV',
    'SZ',
    'TD',
    'TG',
    'TH',
    'TJ',
    'TL',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'US',
    'UY',
    'UZ',
    'VC',
    'VE',
    'VN',
    'VU',
    'WS',
    'XK',
    'ZA',
    'ZM',
    'ZW',
  ],
  copyrights: [
    {
      text: 'Distributed by Warner Music Latina, © 2022 JM WORLD MUSIC - CIGOL',
      type: 'C',
    },
    {
      text: 'Distributed by Warner Music Latina, ℗ 2022 JM WORLD MUSIC - CIGOL',
      type: 'P',
    },
  ],
  external_ids: {
    upc: '5054197415906',
  },
  external_urls: {
    spotify: 'https://open.spotify.com/album/4PR6koe67C7YosjAYriYh4',
  },
  genres: [],
  href: 'https://api.spotify.com/v1/albums/4PR6koe67C7YosjAYriYh4',
  id: '4PR6koe67C7YosjAYriYh4',
  images: [
    {
      height: 640,
      url: 'https://i.scdn.co/image/ab67616d0000b2734c88949535e3089844c61219',
      width: 640,
    },
    {
      height: 300,
      url: 'https://i.scdn.co/image/ab67616d00001e024c88949535e3089844c61219',
      width: 300,
    },
    {
      height: 64,
      url: 'https://i.scdn.co/image/ab67616d000048514c88949535e3089844c61219',
      width: 64,
    },
  ],
  label: 'WEA Latina',
  name: 'Siempre Blessd',
  popularity: 68,
  release_date: '2022-11-03',
  release_date_precision: 'day',
  total_tracks: 13,
  tracks: {
    href: 'https://api.spotify.com/v1/albums/4PR6koe67C7YosjAYriYh4/tracks?offset=0&limit=50&locale=es-419,es',
    items: [
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX',
            },
            href: 'https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX',
            id: '1TA5sGRlKUJXBN4ZyJuDIX',
            name: 'Blessd',
            type: 'artist',
            uri: 'spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 170531,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/6oPzWRP2VSZf8EMq5WeL03',
        },
        href: 'https://api.spotify.com/v1/tracks/6oPzWRP2VSZf8EMq5WeL03',
        id: '6oPzWRP2VSZf8EMq5WeL03',
        is_local: false,
        name: 'Barrio Antioquia',
        preview_url: 'https://p.scdn.co/mp3-preview/3f70d0a01d69dead4d32c48494920671247468ec?cid=1a742ee646b74af4a2a648a825f35326',
        track_number: 1,
        type: 'track',
        uri: 'spotify:track:6oPzWRP2VSZf8EMq5WeL03',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX',
            },
            href: 'https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX',
            id: '1TA5sGRlKUJXBN4ZyJuDIX',
            name: 'Blessd',
            type: 'artist',
            uri: 'spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 204444,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/12RaiccXZ5yIDrHt4c5ngZ',
        },
        href: 'https://api.spotify.com/v1/tracks/12RaiccXZ5yIDrHt4c5ngZ',
        id: '12RaiccXZ5yIDrHt4c5ngZ',
        is_local: false,
        name: 'Que Duro',
        preview_url: 'https://p.scdn.co/mp3-preview/82b16c0f3a37c7a21fd2fddfdc66320e2ea2aaf9?cid=1a742ee646b74af4a2a648a825f35326',
        track_number: 2,
        type: 'track',
        uri: 'spotify:track:12RaiccXZ5yIDrHt4c5ngZ',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX',
            },
            href: 'https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX',
            id: '1TA5sGRlKUJXBN4ZyJuDIX',
            name: 'Blessd',
            type: 'artist',
            uri: 'spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 181988,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/3LbiVjqY2chZ0q9oOwbluK',
        },
        href: 'https://api.spotify.com/v1/tracks/3LbiVjqY2chZ0q9oOwbluK',
        id: '3LbiVjqY2chZ0q9oOwbluK',
        is_local: false,
        name: 'Ojitos Rojos',
        preview_url: 'https://p.scdn.co/mp3-preview/6f8980f08853241c0b9ccdd7b43aa613f3adc414?cid=1a742ee646b74af4a2a648a825f35326',
        track_number: 3,
        type: 'track',
        uri: 'spotify:track:3LbiVjqY2chZ0q9oOwbluK',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX',
            },
            href: 'https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX',
            id: '1TA5sGRlKUJXBN4ZyJuDIX',
            name: 'Blessd',
            type: 'artist',
            uri: 'spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/0KPX4Ucy9dk82uj4GpKesn',
            },
            href: 'https://api.spotify.com/v1/artists/0KPX4Ucy9dk82uj4GpKesn',
            id: '0KPX4Ucy9dk82uj4GpKesn',
            name: 'Dalex',
            type: 'artist',
            uri: 'spotify:artist:0KPX4Ucy9dk82uj4GpKesn',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 205463,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/4WTF4MkWJSEeWhTNk3ywPT',
        },
        href: 'https://api.spotify.com/v1/tracks/4WTF4MkWJSEeWhTNk3ywPT',
        id: '4WTF4MkWJSEeWhTNk3ywPT',
        is_local: false,
        name: 'Más Allá',
        preview_url: 'https://p.scdn.co/mp3-preview/4f9e358644e363abbffbabe15b98150192ef81a5?cid=1a742ee646b74af4a2a648a825f35326',
        track_number: 4,
        type: 'track',
        uri: 'spotify:track:4WTF4MkWJSEeWhTNk3ywPT',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX',
            },
            href: 'https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX',
            id: '1TA5sGRlKUJXBN4ZyJuDIX',
            name: 'Blessd',
            type: 'artist',
            uri: 'spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 175000,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/73lC7gD1EKomxcuXRn7qRR',
        },
        href: 'https://api.spotify.com/v1/tracks/73lC7gD1EKomxcuXRn7qRR',
        id: '73lC7gD1EKomxcuXRn7qRR',
        is_local: false,
        name: 'Exclusive',
        preview_url: 'https://p.scdn.co/mp3-preview/dbaad45f071276ae9f74e976c6a436479f90d595?cid=1a742ee646b74af4a2a648a825f35326',
        track_number: 5,
        type: 'track',
        uri: 'spotify:track:73lC7gD1EKomxcuXRn7qRR',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX',
            },
            href: 'https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX',
            id: '1TA5sGRlKUJXBN4ZyJuDIX',
            name: 'Blessd',
            type: 'artist',
            uri: 'spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/18dspUI6gqabm5XCC2RcUD',
            },
            href: 'https://api.spotify.com/v1/artists/18dspUI6gqabm5XCC2RcUD',
            id: '18dspUI6gqabm5XCC2RcUD',
            name: 'SOG',
            type: 'artist',
            uri: 'spotify:artist:18dspUI6gqabm5XCC2RcUD',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 194823,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/4C8KFz9tPZjIsMfFh9NnJ9',
        },
        href: 'https://api.spotify.com/v1/tracks/4C8KFz9tPZjIsMfFh9NnJ9',
        id: '4C8KFz9tPZjIsMfFh9NnJ9',
        is_local: false,
        name: 'Europa',
        preview_url: 'https://p.scdn.co/mp3-preview/c1005abbd281bb1a6650d1728a73c2bc0d4a391a?cid=1a742ee646b74af4a2a648a825f35326',
        track_number: 6,
        type: 'track',
        uri: 'spotify:track:4C8KFz9tPZjIsMfFh9NnJ9',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX',
            },
            href: 'https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX',
            id: '1TA5sGRlKUJXBN4ZyJuDIX',
            name: 'Blessd',
            type: 'artist',
            uri: 'spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/029uS2pMvwk0TsIUTHkyyw',
            },
            href: 'https://api.spotify.com/v1/artists/029uS2pMvwk0TsIUTHkyyw',
            id: '029uS2pMvwk0TsIUTHkyyw',
            name: 'Amaro',
            type: 'artist',
            uri: 'spotify:artist:029uS2pMvwk0TsIUTHkyyw',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 195613,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/0MWYdCwez4qHJok0df6hbV',
        },
        href: 'https://api.spotify.com/v1/tracks/0MWYdCwez4qHJok0df6hbV',
        id: '0MWYdCwez4qHJok0df6hbV',
        is_local: false,
        name: 'Dime',
        preview_url: 'https://p.scdn.co/mp3-preview/35188c0c70668dbb410fe3c761ccaadccc068507?cid=1a742ee646b74af4a2a648a825f35326',
        track_number: 7,
        type: 'track',
        uri: 'spotify:track:0MWYdCwez4qHJok0df6hbV',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX',
            },
            href: 'https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX',
            id: '1TA5sGRlKUJXBN4ZyJuDIX',
            name: 'Blessd',
            type: 'artist',
            uri: 'spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/12vb80Km0Ew53ABfJOepVz',
            },
            href: 'https://api.spotify.com/v1/artists/12vb80Km0Ew53ABfJOepVz',
            id: '12vb80Km0Ew53ABfJOepVz',
            name: 'Ñengo Flow',
            type: 'artist',
            uri: 'spotify:artist:12vb80Km0Ew53ABfJOepVz',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 205714,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/2NrpiW6Kc1XPm9AzmvuxEa',
        },
        href: 'https://api.spotify.com/v1/tracks/2NrpiW6Kc1XPm9AzmvuxEa',
        id: '2NrpiW6Kc1XPm9AzmvuxEa',
        is_local: false,
        name: 'Solitario',
        preview_url: 'https://p.scdn.co/mp3-preview/c0296177941bb99191ba9ea50f4c84cfd2b83511?cid=1a742ee646b74af4a2a648a825f35326',
        track_number: 8,
        type: 'track',
        uri: 'spotify:track:2NrpiW6Kc1XPm9AzmvuxEa',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX',
            },
            href: 'https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX',
            id: '1TA5sGRlKUJXBN4ZyJuDIX',
            name: 'Blessd',
            type: 'artist',
            uri: 'spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/3EiLUeyEcA6fbRPSHkG5kb',
            },
            href: 'https://api.spotify.com/v1/artists/3EiLUeyEcA6fbRPSHkG5kb',
            id: '3EiLUeyEcA6fbRPSHkG5kb',
            name: 'De La Ghetto',
            type: 'artist',
            uri: 'spotify:artist:3EiLUeyEcA6fbRPSHkG5kb',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1TtXnWcUs0FCkaZDPGYHdf',
            },
            href: 'https://api.spotify.com/v1/artists/1TtXnWcUs0FCkaZDPGYHdf',
            id: '1TtXnWcUs0FCkaZDPGYHdf',
            name: 'Darell',
            type: 'artist',
            uri: 'spotify:artist:1TtXnWcUs0FCkaZDPGYHdf',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 243622,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/6HOMz6FCZqLjTg3Eey0vm2',
        },
        href: 'https://api.spotify.com/v1/tracks/6HOMz6FCZqLjTg3Eey0vm2',
        id: '6HOMz6FCZqLjTg3Eey0vm2',
        is_local: false,
        name: 'Instagram - Remix',
        preview_url: 'https://p.scdn.co/mp3-preview/d6dff0c076043061587310704d4c142850cebbef?cid=1a742ee646b74af4a2a648a825f35326',
        track_number: 9,
        type: 'track',
        uri: 'spotify:track:6HOMz6FCZqLjTg3Eey0vm2',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX',
            },
            href: 'https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX',
            id: '1TA5sGRlKUJXBN4ZyJuDIX',
            name: 'Blessd',
            type: 'artist',
            uri: 'spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/7GQDI5Vmxs92RsIRZzYT11',
            },
            href: 'https://api.spotify.com/v1/artists/7GQDI5Vmxs92RsIRZzYT11',
            id: '7GQDI5Vmxs92RsIRZzYT11',
            name: 'Pirlo',
            type: 'artist',
            uri: 'spotify:artist:7GQDI5Vmxs92RsIRZzYT11',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 236110,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/3JYw9n3rJTVQryVz1rwlH4',
        },
        href: 'https://api.spotify.com/v1/tracks/3JYw9n3rJTVQryVz1rwlH4',
        id: '3JYw9n3rJTVQryVz1rwlH4',
        is_local: false,
        name: 'Ziploc (Blessd Version)',
        preview_url: 'https://p.scdn.co/mp3-preview/bbb3ea82bf818c5cbe57d86d92cbfeccccdfc3d4?cid=1a742ee646b74af4a2a648a825f35326',
        track_number: 10,
        type: 'track',
        uri: 'spotify:track:3JYw9n3rJTVQryVz1rwlH4',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX',
            },
            href: 'https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX',
            id: '1TA5sGRlKUJXBN4ZyJuDIX',
            name: 'Blessd',
            type: 'artist',
            uri: 'spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1fctva4kpRbg2k3v7kwRuS',
            },
            href: 'https://api.spotify.com/v1/artists/1fctva4kpRbg2k3v7kwRuS',
            id: '1fctva4kpRbg2k3v7kwRuS',
            name: 'Rvssian',
            type: 'artist',
            uri: 'spotify:artist:1fctva4kpRbg2k3v7kwRuS',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 155294,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/2wmusRbeSfEkMKjT3wG57l',
        },
        href: 'https://api.spotify.com/v1/tracks/2wmusRbeSfEkMKjT3wG57l',
        id: '2wmusRbeSfEkMKjT3wG57l',
        is_local: false,
        name: 'Bottega',
        preview_url: 'https://p.scdn.co/mp3-preview/be6b4a9c6de12f7cecb847e9011b476100649f11?cid=1a742ee646b74af4a2a648a825f35326',
        track_number: 11,
        type: 'track',
        uri: 'spotify:track:2wmusRbeSfEkMKjT3wG57l',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX',
            },
            href: 'https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX',
            id: '1TA5sGRlKUJXBN4ZyJuDIX',
            name: 'Blessd',
            type: 'artist',
            uri: 'spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/0OJB7a56o2eMyB6hOmv6vC',
            },
            href: 'https://api.spotify.com/v1/artists/0OJB7a56o2eMyB6hOmv6vC',
            id: '0OJB7a56o2eMyB6hOmv6vC',
            name: 'Philip Ariaz',
            type: 'artist',
            uri: 'spotify:artist:0OJB7a56o2eMyB6hOmv6vC',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 195237,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/1xUd3t6zmrAC08LrWKEBrC',
        },
        href: 'https://api.spotify.com/v1/tracks/1xUd3t6zmrAC08LrWKEBrC',
        id: '1xUd3t6zmrAC08LrWKEBrC',
        is_local: false,
        name: 'Bandida',
        preview_url: 'https://p.scdn.co/mp3-preview/3fed8b4fd3cbd3a82efac264a3ee4bb500b0c8b8?cid=1a742ee646b74af4a2a648a825f35326',
        track_number: 12,
        type: 'track',
        uri: 'spotify:track:1xUd3t6zmrAC08LrWKEBrC',
      },
      {
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX',
            },
            href: 'https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX',
            id: '1TA5sGRlKUJXBN4ZyJuDIX',
            name: 'Blessd',
            type: 'artist',
            uri: 'spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/7iK8PXO48WeuP03g8YR51W',
            },
            href: 'https://api.spotify.com/v1/artists/7iK8PXO48WeuP03g8YR51W',
            id: '7iK8PXO48WeuP03g8YR51W',
            name: 'Myke Towers',
            type: 'artist',
            uri: 'spotify:artist:7iK8PXO48WeuP03g8YR51W',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/3m5qlPf2OkihLz3dRYnkPA',
            },
            href: 'https://api.spotify.com/v1/artists/3m5qlPf2OkihLz3dRYnkPA',
            id: '3m5qlPf2OkihLz3dRYnkPA',
            name: 'Ovy On The Drums',
            type: 'artist',
            uri: 'spotify:artist:3m5qlPf2OkihLz3dRYnkPA',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 234402,
        explicit: true,
        external_urls: {
          spotify: 'https://open.spotify.com/track/2TCklWS3S4Zg6e2m2MBoYm',
        },
        href: 'https://api.spotify.com/v1/tracks/2TCklWS3S4Zg6e2m2MBoYm',
        id: '2TCklWS3S4Zg6e2m2MBoYm',
        is_local: false,
        name: 'Tendencia Global',
        preview_url: 'https://p.scdn.co/mp3-preview/c16d760f93efde6394ce6be76a03d7214db1165d?cid=1a742ee646b74af4a2a648a825f35326',
        track_number: 13,
        type: 'track',
        uri: 'spotify:track:2TCklWS3S4Zg6e2m2MBoYm',
      },
    ],
    limit: 50,
    next: null,
    offset: 0,
    previous: null,
    total: 13,
  },
  type: 'album',
  uri: 'spotify:album:4PR6koe67C7YosjAYriYh4',
};
